### PR TITLE
Add support for MicroPython

### PR DESCRIPTION
**Pull request by amotl**
Dear Paweł,

we are using your module within our datalogger appliance on MicroPython. While the Python 3.x is pretty much complete, the standard library has some gaps. The attached patch takes care of that and makes the module happy to run on MicroPython.

We are humbly asking if you are willing to take this. If we could mainline it, we could save on little patches like [`dotty_dict-01.patch`](https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/0.5.1/tools/dotty_dict-01.patch).

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/hiveeyes-micropython-firmware

### CODE REVIEW

**Comment by pawelzny** [comment]
I don't mind to merge this PR, but I afraid that future changes may brake micropython builds. 
Could you prepare micropython docker image and new CI job for it?

I'm using CircleCI which is now configured to run workflow on pull requests from forks.
You can find configuration in: https://github.com/pawelzny/dotty_dict/blob/master/.circleci/config.yml
When CI asures that everything always works on micropython you can also add new classifire 
to `setup.py`.

```
Programming Language :: Python :: Implementation :: MicroPython
````

If you don't care about future incompatibilities, I can merge this PR right away.

**Comment by amotl** [comment]
Dear Paweł,

thanks for your willingness to support MicroPython for the `dotty_dict` library. We don't expect any further incompatibilities coming up as the library is pretty mature (thanks!) and the caring was just about doing the imports in a graceful way.

We might well look into preparing a MicroPython CI job to be aligned with this repository but for now we would just be happy to get things straight at [1].

> If you don't care about future incompatibilities, ...

Well, we **are** willing to take care in the future and will be able to put some humble efforts into keeping it compatible. If this eventually will start getting painful, we will be more than happy to contribute an appropriate test coverage by adding MicroPython support to the CircleCI configuration, which we enabled and started using just recently for the projects [2] and [3].

> ... I can merge this PR right away.

If you are okay with that, then we would like it, yes. Please let us know if we should add this fact to the list of trove classifier this project is tagged with (as you suggested) and if we should mention the same fact at some place within the documentation.

Thanks again and with kind regards,
Andreas.

[1] https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/7c84aa616c59c06ca5d24b48ff9b50506635a727/Makefile#L63-L67
[2] https://github.com/hiveeyes/grafana-worldmap-panel
[3] https://github.com/hiveeyes/dwdweather2

**Comment by amotl** [comment]
Dear Paweł,

after some short research, we have to conclude that there might not be such a thing as testing against MicroPython on CircleCI. While there actually is a MicroPython for Unix [1], we believe it would be difficult to make `pytest` work on MicroPython. However, this is just a guesstimation as we haven't been able to find any resources asserting this or tell about the opposite.

So, we should not expect to get any confidence from test coverage as there might be a road block in plain sight. However, we will be happy to learn otherwise how to manage that.

With kind regards,
Andreas.

[1] https://github.com/micropython/micropython#the-unix-version

**Comment by pawelzny** [comment]
Dear Andreas,
Thank you very much for contribution and research. I've never work with MicroPython and I thought it will be strait forward to prepare such testing environment.

I am accepting this pull request.

**Comment by amotl** [comment]
Thanks, Paweł. We added a short introduction about the Dotty Dict package to our collaborative workspace [1] to give you appropriate credits. Keep up the spirit!

[1] https://community.hiveeyes.org/t/terkin-for-micropython/233/20

**Comment by pawelzny** [comment]
I love it <3 
It means a lot for me. Thank you!

**Pull request merged**
